name: Push app image to dockerhub.
on:
  push:
    branches:
      - main
      - DEVOPS-2
    workflow_run:
      workflows: ["Test and build spring project"]
      types:
        - completed

jobs:
  deploy:
    name: Push image with jar to dockerhub
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug
    needs: build
    permissions:
      contents: read
    steps:
      - name: Download jar from build workflow.
        uses: actions/download-artifact@v4
        with:
          name: horus-app
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: List for test
        run: |
          ls -la
      - name:
        run: |
          cat <<EOF > /kaniko/.docker/config.json
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "$(echo -n "${{ secrets.DOCKERHUB_LOGIN }}:${{ secrets.DOCKERHUB_TOKEN }}" | base64 )"
              }
            }
          }
          EOF

          /kaniko/executor --dockerfile="./docker/Dockerfile.runtime" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
            --destination="$DOCKER_IMAGE_NAME:$(echo ${GITHUB_SHA} | head -c 7)" \
            --destination="$DOCKER_IMAGE_NAME:${{ github.ref_name }}-latest" \
            ${{ env.KANIKO_CACHE_ARGS }} \
            --push-retry 5

        env:
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_IMAGE_NAME: "aborekabits/horus-app"
