name: Scheduled integration tests of spring project

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/2 * * * *'

env:
  HORUS_APP_HOST_PORT: 8080
  HORUS_APP_CONTAINER_PORT: 8080
  DOCKER_IMAGE_NAME: "aborekabits/horus-app"

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run latest app
        run: docker run -p $HORUS_APP_HOST_PORT:$HORUS_APP_CONTAINER_PORT --name horus-app $DOCKER_IMAGE_NAME:main-latest
      
      - name: Test with some timeout to let app start
        run: |
          for i in {1..10}; do
            if curl -s localhost:$HORUS_APP_HOST_PORT | grep -q "Hello world Horus!"; then
              echo "Expected message. Test passed."
              exit 0
            else
              echo "Waiting for startup"
              sleep 3
            fi
          done
          echo "No response in time."
          docker logs horus-app
          exit 1
