name: Release build
on:
  push:
    branches:
      - main
      - 'release*'
    paths:
      - version

permissions:
  contents: write

jobs:
  release:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version
        id: read_version
        run: |
          version=$(grep '^version=' version | cut -d= -f2)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git tag -a "v${{ steps.read_version.outputs.version }}" -m "Number: ${{ github.run_number }}"
          git push origin "v${{ steps.read_version.outputs.version }}"
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          TAG: "v${{ steps.read_version.outputs.version }}"
          IMAGE: "aborekabits/horus-app"
        run: |
          gh release create "${TAG}" \
            --repo "${REPOSITORY}" \
            --title "${REPOSITORY#*/} ${TAG#v}" \
            --target ${{ github.ref_name }} \
            --notes "Docker image for release: https://hub.docker.com/r/${IMAGE}/tags?name=${{ github.ref_name }}-$(echo ${GITHUB_SHA} | head -c 7)"
